# Generated by Django 4.0.4 on 2022-05-01 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('euro', models.CharField(max_length=20)),
                ('real', models.CharField(max_length=20)),
                ('yen', models.CharField(max_length=20)),
            ],
        ),
    ]
